### PR TITLE
adding basic support to relative timestamps

### PR DESCRIPTION
**Pull request by pruski**

### CODE REVIEW

**Comment by odino** [comment]
hey @pruski thanks for this! What about using moment for generating the timestamps?

At that point we can just use something like this `{% moment(...) %}` in the mockfiles. Thoughts?

**Comment by pruski** [comment]
Hi @odino,

In my case, using moment would be an overkill. Using it the way you proposed would mean you will most likely need to manipulate the date, and format the output eg. `{% moment( ).subtract(7, 'days').valueOf( ) %}`. We can easily make it work with eval.

Is that what you think of?

**Comment by odino** [comment]
I was thinking of a small utility function such as `time(relativeUnit)` ie `time('-3d')` or similar

**Comment by pruski** [comment]
Ah, nice. What units you think we should cover?

**Comment by odino** [comment]
I think anything we could feed back to moment, something like:

``` javascript
function func(string) {
  var stringParts = string.match(/[a-zA-Z]+|[0-9]+/g);
  if (!stringParts[1]) {
    stringParts[1] = 's';
  }

  return moment().subtract(stringParts[0], stringParts[1]);
};

func('3d') // etc etc
```

**Pull request closed without merging**
