### PR TITLE
Support importing js files

### PR DESCRIPTION
**Pull request by tbouchnafa**
Hi, 

it would be nice if this would be accepted. 
This will allow to create dynamic responses (my use case is returning a token with an expire time)

Kind regards

### CODE REVIEW

**Comment by odino** [comment]
:+1:

**Comment by tbouchnafa** [comment]
Thanks @odino

**Comment by ioannisGiak89** [comment]
Struggling to get this working. I am getting the import string as a response

**Comment by ioannisGiak89** [comment]
Sorry issue solved

**Comment by Wimpje** [comment]
For others that run into this, also include the trailing semicolon ; ;-)

**Pull request merged**
