### PR TITLE
Verbose output by default and silent option

### PR DESCRIPTION
**Pull request by jaymecd**
Verbose output shows if mock file has matched or not.

```
Reading from ../../api/GET.mock file: Matched
Reading from ../../api/test/GET.mock file: Not matched
```

### CODE REVIEW

**Comment by mohdhallal** [comment]
thanks for the work @jaymecd 

would you kindly update the documentation about this option, should be good to go after that.

**Comment by odino** [comment]
BTW @jaymecd I just reverted this since it was merged by mistake -- as @mohdhallal said, if you could update the README and then we're good to go :)

**Comment by unlucio** [comment]
ouch, my bad: early morning merging and I messed up project.
Sorry guys :(

**Comment by odino** [comment]
no probs! :)

**Pull request merged**
