### PR TITLE
Json body separate file

### LINKED ISSUE #38: JSON payloads
When posting JSON in the body, the filename matcher attempts to match the entire body of the payload as the filename.

This has some repercussions on  windows as many characters are invalid:

```
Reading from mocks/POST--{"data":{"index":0,"max":25},"sortBy":["name"]}.mock file: Not matched
```

I wonder if there are any alternative ways to match payloads to requests?

### PR DESCRIPTION
**Pull request by joshmorel**
Resolves #38 

@odino  - sorry for the delay, we decided to go with a different option but I figured I should follow up on the offer nonetheless!

@artsyca - can you try this out to make sure it will meet your need on Windows.

### CODE REVIEW

**Comment by odino** [comment]
Some of the tests dont seem to pass -- can you have a look? :)

**Comment by joshmorel** [comment]
Ah I see. I didn't look at the .travis.yml but wouldn't have thought you'd be supporting for less than 6.... but I guess 4's end of life still isn't til April 30th. None the less it should be an easy substitution.

**Comment by odino** [comment]
BTW, if it's easy fixes let's make sure the build passes, whereas if you think it's not worth the effort we can drop support for old versions :)

**Comment by artsyca** [comment]
Incredibly kind of you to look into this @joshmorel. I am away for a couple of weeks but will gladly investigate in mid may if that serves?

**Comment by cirpo** [comment]
still open? shall we still support node <6?

**Comment by odino** [comment]
Closing this for inactivity

**Pull request closed without merging**
