### PR TITLE
Added trim() call to all headers to watch

### PR DESCRIPTION
**Pull request by kkoehler**
Added a trim() call to all headers which should be watched inside "prepareWatchedHeaders". Setting environment entry in windows adds a space to the last value.

For example
---
set MOCK_HEADERS=auth && mockserver ...
---

will fail because the header is 'auth ' (space at the end)

### CODE REVIEW

**Comment by odino** [comment]
Hi @kkoehler, thanks for this! It looks like the PR has some conflicts, would you mind resolving those?

**Comment by kkoehler** [comment]
Fixed the merge conflict. The test failures are "imported/merged" from master...

**Comment by odino** [comment]
Hi @kkoehler -- tests are still failing :)

**Comment by odino** [comment]
Closing this for inactivity

**Pull request closed without merging**
